spring:
  # 数据连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 980307
  application:
    name: knife4j
  # redis配置信息
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    connect-timeout: 1000
    # 密码 默认为空
#    password:
    # 用户名 默认为空
#    username:
knife4j:
  enable: true
  setting:
    enableSwaggerModels: true
    swaggerModelName: 我是自定义的Model名称
  base-packge: com.spring.portal
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      # 设置mybatis-plus新增策略, not_empty 不允许为空
      insert-strategy: not_empty
      # 设置mybatis-plus更新策略, not_empty 不允许为空
      update-strategy: not_null
      # 驼峰下划线转换
      table-underline: true
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑不删除值
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath*:com/spring/**/xml/*Mapper.xml